name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y meson ninja-build gcc pkg-config \
        wayland-protocols libwayland-dev libxkbcommon-dev \
        libwlroots-dev libconfig-dev libjson-c-dev libwlroots-dev

    - name: Configure the project with Meson
      run: meson setup build

    - name: Build the project
      run: meson compile -C build
